---
title: 'Chapter 3: How to ask for help'
description:
  'Places to find help with troubleshooting R, useful resources, and how ask clear questions with minimally reproducible examples.'
prev: /chapter2
next: /chapter4
type: chapter
id: 3
output:
  teachr::teachr_chapter:
  html_document:
    self_contained: true
---

```{r setup, include = FALSE}
library(teachr)
library(tidyverse)
knitr::knit_hooks$set(class = function(before, options, envir) {
  if(before) {
    sprintf("<div class='%s'>", options$class)
  } else {
    "</div>"
  }
})
knitr::opts_chunk$set(fig.retina = 2,
                      fig.width = 6, 
                      fig.height = 4,
                      fig.align = "center",
                      cache = TRUE,
                      cache.path = "cache/",
                      message = FALSE,
                      warning = FALSE)
```

<exercise id="1" title="The first exercise with slides" type="slides">

`r slides("slides_example")`

</exercise>

<exercise id="2" title="The second exercise with tasks">

Which of the following are `TRUE`?

```{r, echo = FALSE}
mc_opts("TRUE" = "Well done! TRUE is TRUE!",
        "FALSE" = "Sorry, that's wrong. FALSE is not TRUE!",
        correct = 1)
```

Update the following code to produce a boxplot of fuel efficiency (`mpg`) against the number of cylinders (`cyl`).

```{teachr example}
mtcars %>% 
  ggplot(aes(x = factor(cyl), y = mpg)) + 
  geom_<<boxplot>>()
```
